### ISSUE TITLE
Why limiting RPC to 1?

### ISSUE THREAD

**Issue by vdiez** [kalmyk/fox-wamp#4]
Hello,

according to what I see on:

https://github.com/kalmyk/fox-wamp/blob/1997ab27c55517a4168fa512a2e507a199fcc57d/lib/realm.js#L276

you are limiting to one single call per RPC. Any reason to do that? the WAMP protocol does not limit that explicitly, so you are limiting functionality. In any case, should be unlimited by default and with the posibility to limit it by configuration parameters.

**Comment by kalmyk** [comment]
Simultaneous tasks limit for wamp session made unlimited
