### ISSUE TITLE
fox-wamp cluster

### ISSUE THREAD

**Issue by eportico** [kalmyk/fox-wamp#7]
Hi,
I want design a fox-wamp cluster. I need know how I can access to registered rpc clients to capture rpc demand from another nodes and propagate this request to client who registered that rpc
Thx

**Comment by kalmyk** [comment]
Hello,
Unfortunately there is no easy way to make a cluster. As for now there is no such solution. As I see it much easy to use external fail-over solution from redis for example by https://github.com/mcollina/mosca.
Regards,
Anatoly
